Update style.css as per add-on template
marlon-sousa/EnhancedFindDialog pull request #23
Opened 2023-08-31 08:56 UTC by CyrilleB79

### Issue
The doc of this add-on is using inverted color scheme. This inverted color scheme has been removed from the add-on template; see https://github.com/nvdaaddons/AddonTemplate/issues/4 and https://github.com/nvdaaddons/AddonTemplate/pull/8 for explanations.
Short story: it's better to let each visually impaired person his/her preferred color scheme.

### Solution
Update style.css file as per add-on template.

2023-09-19 21:10 UTC, CyrilleB79 commented
I just realize that this PR is blocked due to workflow approval needed.
Is something expected from me?
Thanks.

2023-09-23 13:32 UTC, marlon-sousa requested changes
Hello,

Please change the addon version to the next minor available in buildvars.py file so that when we merge a new release will be authomatically generated.

Also, if I can ask you, please submit the same changes to the other addons I maintain, the enhancedDictionaries and timerForNVDA. I ask it because you can test it better before submiting and we can be sure that it is working as it should.

2023-09-25 09:31 UTC, CyrilleB79 commented
OK. Version number changed and pushed.

I will take care of the two other add-ons; should I update the version number as well for them?

2023-09-25 11:58 UTC, marlon-sousa approved these changes

2023-09-25 11:59 UTC, merged

2023-09-25 12:15 UTC, marlon-sousa commented
Yes.

Here is how addons supported by me work:

1. You should generate a new version because, as expected, we are generating a new version.
2. When your changes are complete, run scons to generate the new .nvda-addon file if you have your environment setup.
3. We are not interested on the nvda-addon file generated vby you, because this will be generated by continuous integration process. However, when you issue scons, because you changed the version in buildvars.py, you will notice that the readme file will also be changed. This happens because when the readme is generated, it uses variables defined in buildvars.py to do interesting stuff such as generating links.
4. Commit your changes, includiong the new readme file (in this case for this addon I generated tthe commit for the readme file).
5. Then, I will merge into master and generate a tag equals to the new version. Once I push the tag, CI is triggered and a new release is generated. The resulting nvda-addon file will be available at the linjk the update readme file file specifies.

2023-09-25 13:23 UTC, CyrilleB79 commented
OK. I have submitted the two PRs for the two other add-ons.

Note: Since you have a "contributing.md", I suggest that you add there the information you gave me in https://github.com/marlon-sousa/EnhancedFindDialog/pull/23#issuecomment-1733584534.

2023-09-27 11:44 UTC, marlon-sousa commented
Thank you @CyrilleB79  ... all addons have been updated and released accordingly to the new style, with english readme packaged as expected.

Addons will be submitted to addon store shortly!